import { Injectable } from '@angular/core';
import { Performance, Session, Availability, Seat } from '../shared/performance.model';
import { Subject } from 'rxjs/Subject';

@Injectable()
export class PerformanceService {
	performancesChanged = new Subject<Performance[]>();

	performanceChanged = new Subject<{performance: Performance, id: number}>();
	sessionChanged = new Subject<{session: Session, id: number}>();

	// this should be changed later (from DB)
	// get this at start
	private performances:Performance[] = [
		new Performance("Blocked", "Can you survive the air?", [
		new Session(new Date(2017, 12, 1),
			[
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Booked),
					new Seat(Availability.Booked),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Booked),
					new Seat(Availability.Available),
					new Seat(Availability.Hidden),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Booked),
					new Seat(Availability.Available),
					new Seat(Availability.Booked),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Hidden),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Hidden),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Hidden),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Hidden),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ], 
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ]
			]),
		new Session(new Date(2018, 11, 18),
			[
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ], 
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ]
			]),
		]),
		new Performance("Second Performance", "My very very veryv very veryv long long long long long long long long long long long long long long desriptino!", [
		new Session(new Date(2019, 8, 12),
			[
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ], 
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ]
			]),
		new Session(new Date(2020, 1, 8),
			[
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ], 
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ]
			]),
		]),
		,
	];

	// should be initialized elsewhere!
	private selectedPerformanceId: number;
	private selectedSessionId: number;

	public selectedPerformance(): Performance {
		return this.performances[this.selectedPerformanceId];
	}

	public selectedSession(): Session {
		return this.performances[this.selectedPerformanceId].sessions[this.selectedSessionId];
	}

	public selectPerformance(id: number): void {
		this.selectedPerformanceId = id;
		this.performanceChanged.next({
			performance: this.selectedPerformance(),
			id: this.selectedPerformanceId
		});
	}

	public selectSession(id: number): void {
		this.selectedSessionId = id;
		this.sessionChanged.next({
			session: this.selectedSession(),
			id: this.selectedSessionId
		});
	}

	public selectPS(pid: number, sid: number): void {
		this.selectedPerformanceId = pid;
		this.selectedSessionId = sid;
		this.performanceChanged.next({
			performance: this.selectedPerformance(),
			id: this.selectedPerformanceId
		});
		this.sessionChanged.next({
			session: this.selectedSession(),
			id: this.selectedSessionId
		});	
	}



	constructor() {
		console.log('y');
	}

	// TODO: this should be gotten from server
	// constructor(private performances: Performance[]) {}
	public getPerformances(): Performance[] {
		return this.performances.slice();
	}

	public getPerformance(pid: number): Performance {
		if (pid > this.performances.length - 2)
			throw "Performance ID exceeds total number of performances!";
		if (pid < 0)
			throw "Performance ID is less then zero!";
			
		return this.performances[pid];
	}

	public addPerformance(Performance: Performance): void {
		this.performances.push(Performance);
		this.performancesChanged.next(this.performances.slice());
	}

	public updatePerformance(id: number, Performance: Performance): void {
		this.performances[id] = Performance;
		this.performancesChanged.next(this.performances.slice());
	}

	public deletePerformance(id: number): void {
		this.performances.splice(id, 1);
		this.performancesChanged.next(this.performances.slice());
	}

	public loadPerformances(performances: Performance[]): void {
		this.performances = performances;
		this.performancesChanged.next(this.performances.slice());
	}
}