import { Injectable } from '@angular/core';
import { Performance, Session, Availability, Seat } from '../shared/performance.model';
import { Subject } from 'rxjs/Subject';

@Injectable()
export class PerformanceService {
	performancesChanged = new Subject<Performance[]>();

	// this should be changed later (from DB)
	private performances:Performance[] = [
		new Performance("Blocked", "Can you survive the air?", [
		new Session(new Date(2017, 12, 1),
			[
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ], 
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ]
			]),
		new Session(new Date(2018, 11, 18),
			[
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ], 
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ]
			]),
		]),
		new Performance("Second Performance", "My very very veryv very veryv long long long long long long long long long long long long long long desriptino!", [
		new Session(new Date(2019, 8, 12),
			[
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ], 
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ]
			]),
		new Session(new Date(2020, 1, 8),
			[
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ], 
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ],
				[ new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					new Seat(Availability.Available),
					 ]
			]),
		]),
		,
	];

	

	constructor() {}

	getPerformances(): Performance[] {
		return this.performances.slice();
	}

	getPerformance(pid: number): Performance {
		if (pid > this.performances.length - 2)
			throw "Performance ID exceeds total number of performances!";
		if (pid < 0)
			throw "Performance ID is less then zero!";
			
		return this.performances[pid];
	}

	addPerformance(Performance: Performance): void {
		this.performances.push(Performance);
		this.performancesChanged.next(this.performances.slice());
	}

	updatePerformance(id: number, Performance: Performance): void {
		this.performances[id] = Performance;
		this.performancesChanged.next(this.performances.slice());
	}

	deletePerformance(id: number): void {
		this.performances.splice(id, 1);
		this.performancesChanged.next(this.performances.slice());
	}

	loadPerformances(performances: Performance[]): void {
		this.performances = performances;
		this.performancesChanged.next(this.performances.slice());
	}
}